### ISSUE TITLE
Video presentation from PPT slides

### ISSUE THREAD

**Issue by vladimirkovacevic** [RixRasa/Genomics#3]
After 7 years this is the first time that someone made video without utilising slides that were created. I must say it was not explicitly defined in text of the project, but, still, it should be much easier. After all, that is why the slides are created at the first place.

**Comment by RixRasa** [comment]
Hello,

Thank you for bringing this to our attention. I apologize for any inconvenience caused by the recent video that did not use the pre-existing slides. I appreciate your point about the importance of using these resources to improve our presentations and make them more effective.

Best regards,
Raša Stojanović

**Comment by vladimirkovacevic** [comment]
Thanks!
